# fly.toml app configuration file generated for snowy-dawn-7436 on 2023-07-20T12:59:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-dawn-7436"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
